name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest # Or a specific version like mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mydb # Optional: create a specific database
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4' # Or your Go version
      - name: Install dependencies
        run: cd src && go mod download
      - name: Run tests
        env:
          DB_USER: root
          DB_PASSWORD: password
          DB_NAME: mydb
          HOST: 0.0.0.0
          PORT: 8080
          JWT_SECRET_KEY: secret
        run: go test ./*/*/
